# Generated by Django 5.2.6 on 2025-09-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Enter skills separated by commas', null=True),
        ),
    ]
