# Generated by Django 5.2.6 on 2025-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_alter_freelancerprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level (0-2 years)'), ('intermediate', 'Intermediate (2-5 years)'), ('expert', 'Expert (5+ years)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='professional_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
