# Generated by Django 5.2.6 on 2025-09-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_freelancerprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
