# Generated by Django 5.2.6 on 2025-09-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_freelancerprofile_github_freelancerprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('caption', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_posts', to='freelancer.freelancerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
