# Generated by Django 4.2.20 on 2025-09-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_remove_application_freelancer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='freelancer.freelancerprofile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate_name',
            field=models.CharField(default='Unknown Candidate', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='freelancer.job'),
        ),
    ]
