# Generated by Django 4.2.20 on 2025-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0009_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
