# Generated by Django 5.2.6 on 2025-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0013_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_accepted', 'Application Accepted'), ('application_rejected', 'Application Rejected'), ('new_job', 'New Job Available'), ('new_application', 'New Application Received'), ('message', 'New Message'), ('system', 'System Notification')], max_length=50),
        ),
    ]
