# Generated by Django 5.2.6 on 2025-10-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0018_airequestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('application', 'Application Based'), ('acceptance', 'Acceptance Based'), ('profile', 'Profile Based'), ('login', 'Login Based')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('icon', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_on', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.badge')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='freelancer.freelancerprofile')),
            ],
            options={
                'unique_together': {('freelancer', 'badge')},
            },
        ),
    ]
