# Generated by Django 5.2.6 on 2025-10-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0019_badge_freelancerbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
