# Generated by Django 5.2.6 on 2025-10-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0020_freelancerprofile_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
    ]
