# Generated by Django 5.2.6 on 2025-10-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0021_freelancerprofile_login_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='longitude',
        ),
    ]
