# Generated by Django 5.2.6 on 2025-10-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0022_remove_freelancerprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='timezone',
        ),
    ]
