# Generated by Django 5.2.6 on 2025-10-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0023_remove_freelancerprofile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='country',
        ),
    ]
