# Generated by Django 5.2.6 on 2025-10-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0024_remove_freelancerprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='timezone',
            field=models.CharField(blank=True, default='IST', max_length=50, null=True),
        ),
    ]
