# Generated by Django 5.2.6 on 2025-10-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0025_freelancerprofile_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('demand_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
