# Generated by Django 5.2.6 on 2025-10-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0026_skilldemand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilldemand',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='skilldemand',
            name='skill_name',
            field=models.CharField(max_length=100),
        ),
    ]
