# Generated by Django 4.2.20 on 2025-10-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0028_project_task_taskcomment_delete_skilldemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20),
        ),
    ]
