# Generated by Django 4.2.20 on 2025-10-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0029_task_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
