# Generated by Django 4.2.20 on 2025-10-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0030_freelancerprofile_total_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
