# Generated by Django 4.2.20 on 2025-10-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0031_alter_freelancerprofile_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='rank_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='task_completion_rate',
            field=models.FloatField(default=0),
        ),
    ]
