# Generated by Django 4.2.20 on 2025-10-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0033_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='client_company',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_position',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='freelancer.freelancerprofile'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True),
        ),
    ]
